(define-library (realworld scenario articles)
  (export expected-http-requests)
  (import (scheme base))
  (begin
(define expected-http-requests
  '((1 "DELETE" "/api/articles/{slug}" 204)
    (6 "GET" "/api/articles" 200)
    (3 "GET" "/api/articles/{slug}" 200)
    (1 "GET" "/api/articles/{slug}" 404)
    (1 "GET" "/api/tags" 200)
    (1 "POST" "/api/articles" 201)
    (1 "POST" "/api/users" 201)
    (3 "PUT" "/api/articles/{slug}" 200)
    (1 "PUT" "/api/articles/{slug}" 422)))
  ))
