(define-library (realworld scenario errors_authorization)
  (export expected-http-requests)
  (import (scheme base))
  (begin
(define expected-http-requests
  '((1 "DELETE" "/api/articles/{slug}" 204)
    (1 "DELETE" "/api/articles/{slug}" 403)
    (1 "DELETE" "/api/articles/{slug}/comments/{comment_id}" 403)
    (1 "GET" "/api/articles/{slug}/comments" 200)
    (1 "GET" "/api/tags" 200)
    (1 "POST" "/api/articles" 201)
    (1 "POST" "/api/articles/{slug}/comments" 201)
    (2 "POST" "/api/users" 201)
    (1 "PUT" "/api/articles/{slug}" 403)))
  ))
