(define-library (realworld scenario errors_auth)
  (export expected-http-requests)
  (import (scheme base))
  (begin
(define expected-http-requests
  '((1 "GET" "/api/tags" 200)
    (1 "GET" "/api/user" 401)
    (1 "POST" "/api/users" 201)
    (2 "POST" "/api/users" 409)
    (3 "POST" "/api/users" 422)
    (1 "POST" "/api/users/login" 401)
    (2 "POST" "/api/users/login" 422)
    (2 "PUT" "/api/user" 200)
    (1 "PUT" "/api/user" 401)
    (7 "PUT" "/api/user" 422)))
  ))
