(define-library (realworld scenario errors_articles)
  (export expected-http-requests)
  (import (scheme base))
  (begin
(define expected-http-requests
  '((2 "DELETE" "/api/articles/{slug}" 204)
    (1 "DELETE" "/api/articles/{slug}" 401)
    (1 "DELETE" "/api/articles/{slug}" 404)
    (1 "DELETE" "/api/articles/{slug}/favorite" 401)
    (1 "DELETE" "/api/articles/{slug}/favorite" 404)
    (1 "GET" "/api/articles/feed" 401)
    (1 "GET" "/api/articles/{slug}" 404)
    (1 "GET" "/api/tags" 200)
    (2 "POST" "/api/articles" 201)
    (1 "POST" "/api/articles" 401)
    (3 "POST" "/api/articles" 422)
    (1 "POST" "/api/articles/{slug}/favorite" 401)
    (1 "POST" "/api/articles/{slug}/favorite" 404)
    (1 "POST" "/api/users" 201)
    (1 "PUT" "/api/articles/{slug}" 401)
    (2 "PUT" "/api/articles/{slug}" 404)))
  ))
