load("@rules_go//go:def.bzl", "go_binary", "go_library")
load("@rules_itest//:itest.bzl", "itest_service", "service_test")
load(":hurl_test.bzl", "realworld_hurl_test")
load(":oci_rootfs.bzl", "oci_rootfs")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "oci_bundle_lib",
    srcs = ["oci_bundle.go"],
    importpath = "github.com/hannah-barbera/rules_stests/bazel/itest/oci_bundle",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "oci_bundle",
    embed = [":oci_bundle_lib"],
)

go_library(
    name = "api_probe_lib",
    srcs = ["api_probe.go"],
    importpath = "github.com/hannah-barbera/rules_stests/bazel/itest/api_probe",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "api_probe",
    embed = [":api_probe_lib"],
)

go_library(
    name = "hurl_test_driver_lib",
    srcs = ["hurl_test_driver.go"],
    importpath = "github.com/hannah-barbera/rules_stests/bazel/itest/hurl_test_driver",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "realworld_hurl",
    data = [
        ":hurl_rootfs",
        "@realworld_api_specs//:hurl_all",
    ],
    embed = [":hurl_test_driver_lib"],
)

oci_rootfs(
    name = "aiohttp_rootfs",
    image = "@aiohttp_realworld_linux_amd64",
    single_payload = True,
)

oci_rootfs(
    name = "django_rootfs",
    image = "@django_ninja_realworld_linux_amd64",
    single_payload = True,
)

oci_rootfs(
    name = "hurl_rootfs",
    image = "@hurl_tool_linux_amd64",
)

itest_service(
    name = "aiohttp_service",
    args = [
        "app",
        "aiohttp",
        "$(rootpath :aiohttp_rootfs)",
        "serve",
        "--host",
        "127.0.0.1",
        "--port",
        "$${PORT}",
    ],
    autoassign_port = True,
    data = [":aiohttp_rootfs"],
    exe = ":oci_bundle",
    expected_start_duration = "3s",
    http_health_check_address = "http://127.0.0.1:$${PORT}/api/tags",
    shutdown_timeout = "10s",
)

service_test(
    name = "aiohttp_test",
    args = ["--service-suffix=//bazel/itest:aiohttp_service"],
    services = [":aiohttp_service"],
    test = ":api_probe",
    timeout = "moderate",
)

realworld_hurl_test(
    name = "aiohttp_hurl_test",
    service = ":aiohttp_service",
    specs = "@realworld_api_specs//:hurl_all",
    timeout = "moderate",
)

itest_service(
    name = "django_service",
    args = [
        "app",
        "django",
        "$(rootpath :django_rootfs)",
        "serve",
        "--host",
        "127.0.0.1",
        "--port",
        "$${PORT}",
    ],
    autoassign_port = True,
    data = [":django_rootfs"],
    exe = ":oci_bundle",
    expected_start_duration = "3s",
    http_health_check_address = "http://127.0.0.1:$${PORT}/api/tags",
    shutdown_timeout = "10s",
)

service_test(
    name = "django_test",
    args = ["--service-suffix=//bazel/itest:django_service"],
    services = [":django_service"],
    test = ":api_probe",
    timeout = "moderate",
)

realworld_hurl_test(
    name = "django_hurl_test",
    service = ":django_service",
    specs = "@realworld_api_specs//:hurl_all",
    timeout = "moderate",
)
