[package]
name = "otel-sink"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "otel-sink"
path = "otel_sink/main.rs"

[dependencies]
emballoc = "0.3.0"
prost = { version = "0.14.4", default-features = false, features = ["derive"] }
rustix = { version = "1.1.4", default-features = false, features = ["alloc", "fs", "net", "runtime", "stdio", "time"] }
serde = { version = "1.0.228", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0.145", default-features = false, features = ["alloc"] }
