source "https://rubygems.org"

ruby "3.3.12"

gem "rails", "8.1.3.1"
gem "sqlite3", "~> 2.7"
gem "puma", "~> 7.1"
gem "bcrypt", "~> 3.1"
gem "jwt", "~> 3.1"

group :test do
  gem "minitest", "~> 5.25"
end
