load("@rules_shell//shell:sh_binary.bzl", "sh_binary")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

package(default_visibility = ["//visibility:public"])

sh_binary(
    name = "assemble_otel_report",
    srcs = ["assemble_otel_report.sh"],
)

sh_test(
    name = "local_oci_repository_test",
    srcs = ["local_oci_repository_test.sh"],
    data = [
        "local_oci_repository.py",
        "local_oci_repository_test.py",
    ],
)
